// Package mediaorganizer - 智能媒体整理器
// 对标群晖 Synology Photos，增强：AI 场景识别、自动相册、重复检测
package mediaorganizer

import (
	"fmt"
	"net/http"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
)

// Manager 媒体整理管理器
type Manager struct {
	mu       sync.RWMutex
	config   *Config
	albums   map[string]*Album
	tags     map[string]*Tag
	dupes    []*DuplicateGroup
	stats    *MediaStats
}

// Config 配置
type Config struct {
	Enabled         bool     `json:"enabled"`
	WatchPaths      []string `json:"watch_paths"`
	AutoOrganize    bool     `json:"auto_organize"`
	AIEnabled       bool     `json:"ai_enabled"`
	DupeDetection   bool     `json:"dupe_detection"`
	ThumbSizes      []int    `json:"thumb_sizes"`
	ExcludePatterns []string `json:"exclude_patterns"`
}

// Album 相册
type Album struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        string    `json:"type"` // manual, ai_scene, ai_face, ai_time, smart
	CoverPath   string    `json:"cover_path"`
	MediaCount  int       `json:"media_count"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Tags        []string  `json:"tags"`
	SmartRule   *SmartRule `json:"smart_rule,omitempty"`
}

// SmartRule 智能规则
type SmartRule struct {
	Type      string   `json:"type"` // scene, face, location, time, tag
	Values    []string `json:"values"`
	MatchMode string   `json:"match_mode"` // any, all
}

// Tag 标签
type Tag struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Count      int    `json:"count"`
	Category   string `json:"category"` // scene, object, place, custom
	AutoGenerated bool `json:"auto_generated"`
}

// DuplicateGroup 重复组
type DuplicateGroup struct {
	ID        string   `json:"id"`
	Files     []string `json:"files"`
	TotalSize int64    `json:"total_size"`
	SaveSize  int64    `json:"saveable_size"`
	Algorithm string   `json:"algorithm"` // perceptual, hash
	Score     float64  `json:"score"`     // 0-100 相似度
}

// MediaStats 媒体统计
type MediaStats struct {
	TotalFiles     int       `json:"total_files"`
	TotalSize      int64     `json:"total_size"`
	PhotoCount     int       `json:"photo_count"`
	VideoCount     int       `json:"video_count"`
	AlbumCount     int       `json:"album_count"`
	TagCount       int       `json:"tag_count"`
	DupGroupCount  int       `json:"dup_group_count"`
	DupSaveSize    int64     `json:"dup_saveable_size"`
	LastScanTime   time.Time `json:"last_scan_time"`
}

// MediaItem 媒体项
type MediaItem struct {
	ID        string    `json:"id"`
	Path      string    `json:"path"`
	Name      string    `json:"name"`
	MimeType  string    `json:"mime_type"`
	Size      int64     `json:"size"`
	Width     int       `json:"width,omitempty"`
	Height    int       `json:"height,omitempty"`
	Duration  float64   `json:"duration,omitempty"` // video duration in seconds
	TakenAt   time.Time `json:"taken_at"`
	Tags      []string  `json:"tags"`
	Albums    []string  `json:"albums"`
	Hash      string    `json:"hash"`
	Thumbnail string    `json:"thumbnail"`
}

// NewManager 创建管理器
func NewManager(config *Config) *Manager {
	return &Manager{
		config: config,
		albums: make(map[string]*Album),
		tags:   make(map[string]*Tag),
		dupes:  make([]*DuplicateGroup, 0),
		stats:  &MediaStats{},
	}
}

// Start 启动管理器
func (m *Manager) Start() error {
	if !m.config.Enabled {
		return nil
	}
	go m.watchLoop()
	go m.scanDuplicates()
	return nil
}

func (m *Manager) watchLoop() {
	ticker := time.NewTicker(5 * time.Minute)
	defer ticker.Stop()
	for range ticker.C {
		m.scanMedia()
	}
}

func (m *Manager) scanMedia() {
	// 实际实现：扫描目录、提取元数据、AI 标签
}

func (m *Manager) scanDuplicates() {
	// 实际实现：感知哈希检测重复
}

// CreateAlbum 创建相册
func (m *Manager) CreateAlbum(name, albumType string) *Album {
	m.mu.Lock()
	defer m.mu.Unlock()
	album := &Album{
		ID:        fmt.Sprintf("album-%d", time.Now().UnixNano()),
		Name:      name,
		Type:      albumType,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	m.albums[album.ID] = album
	m.stats.AlbumCount++
	return album
}

// GetDashboard 获取仪表盘
func (m *Manager) GetDashboard() map[string]interface{} {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return map[string]interface{}{
		"stats":  m.stats,
		"albums": len(m.albums),
		"tags":   len(m.tags),
		"dupes":  len(m.dupes),
	}
}

// Handler HTTP 处理器
type Handler struct {
	manager *Manager
}

func NewHandler(manager *Manager) *Handler {
	return &Handler{manager: manager}
}

func (h *Handler) RegisterRoutes(router *gin.RouterGroup) {
	group := router.Group("/media-organizer")
	{
		group.GET("/dashboard", h.GetDashboard)
		group.GET("/albums", h.ListAlbums)
		group.POST("/albums", h.CreateAlbum)
		group.GET("/albums/:id", h.GetAlbum)
		group.GET("/tags", h.ListTags)
		group.GET("/dupes", h.ListDuplicates)
		group.POST("/dupes/clean", h.CleanDuplicates)
		group.POST("/scan", h.TriggerScan)
	}
}

func (h *Handler) GetDashboard(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"success": true, "data": h.manager.GetDashboard()})
}

func (h *Handler) ListAlbums(c *gin.Context) {
	h.manager.mu.RLock()
	defer h.manager.mu.RUnlock()
	albums := make([]*Album, 0, len(h.manager.albums))
	for _, a := range h.manager.albums {
		albums = append(albums, a)
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": albums})
}

func (h *Handler) CreateAlbum(c *gin.Context) {
	var req struct {
		Name string `json:"name" binding:"required"`
		Type string `json:"type"`
	}
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"success": false, "error": err.Error()})
		return
	}
	if req.Type == "" {
		req.Type = "manual"
	}
	album := h.manager.CreateAlbum(req.Name, req.Type)
	c.JSON(http.StatusCreated, gin.H{"success": true, "data": album})
}

func (h *Handler) GetAlbum(c *gin.Context) {
	id := c.Param("id")
	h.manager.mu.RLock()
	album, ok := h.manager.albums[id]
	h.manager.mu.RUnlock()
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"success": false, "error": "相册不存在"})
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": album})
}

func (h *Handler) ListTags(c *gin.Context) {
	h.manager.mu.RLock()
	defer h.manager.mu.RUnlock()
	tags := make([]*Tag, 0, len(h.manager.tags))
	for _, t := range h.manager.tags {
		tags = append(tags, t)
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": tags})
}

func (h *Handler) ListDuplicates(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"success": true, "data": h.manager.dupes})
}

func (h *Handler) CleanDuplicates(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"success": true, "message": "清理任务已启动"})
}

func (h *Handler) TriggerScan(c *gin.Context) {
	go h.manager.scanMedia()
	c.JSON(http.StatusOK, gin.H{"success": true, "message": "扫描已启动"})
}
