// Package nfs 提供NFS共享服务管理功能
package nfs

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"nas-os/internal/logging"
)

// ConfigParser NFS配置解析器
type ConfigParser struct {
	logger *logging.Logger
}

// NewConfigParser 创建配置解析器
func NewConfigParser() *ConfigParser {
	return &ConfigParser{
		logger: logging.NewLogger(nil).WithSource("nfs-config"),
	}
}

// ParseExportsFile 解析/etc/exports文件
func (p *ConfigParser) ParseExportsFile(path string) ([]*Export, error) {
	file, err := os.Open(path)
	if err != nil {
		p.logger.Errorf("打开exports文件失败: %s - %v", path, err)
		return nil, fmt.Errorf("打开文件失败: %w", err)
	}
	defer func() { _ = file.Close() }()

	var exports []*Export
	scanner := bufio.NewScanner(file)
	lineNum := 0

	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())

		// 跳过空行和注释
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		export, err := p.parseExportLine(line)
		if err != nil {
			p.logger.Warnf("解析第%d行失败: %v", lineNum, err)
			continue
		}

		exports = append(exports, export)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("读取文件失败: %w", err)
	}

	p.logger.Infof("解析了 %d 个导出配置", len(exports))
	return exports, nil
}

// parseExportLine 解析单行导出配置
// 格式: /path host1(options) host2(options) ...
func (p *ConfigParser) parseExportLine(line string) (*Export, error) {
	// 分割路径和客户端配置
	parts := strings.Fields(line)
	if len(parts) < 1 {
		return nil, fmt.Errorf("无效的导出行格式")
	}

	path := parts[0]
	if !filepath.IsAbs(path) {
		return nil, fmt.Errorf("路径必须是绝对路径: %s", path)
	}

	export := &Export{
		Path:    path,
		Clients: []Client{},
		Options: ExportOptions{
			Rw:           true, // 默认读写
			NoRootSquash: false,
			Async:        false,
			Secure:       false,
			SubtreeCheck: false,
		},
	}

	// 解析客户端配置
	for i := 1; i < len(parts); i++ {
		client, err := p.parseClientSpec(parts[i])
		if err != nil {
			p.logger.Warnf("解析客户端配置失败: %s - %v", parts[i], err)
			continue
		}
		export.Clients = append(export.Clients, *client)
	}

	return export, nil
}

// parseClientSpec 解析客户端规格
// 格式: host(options) 或 host
func (p *ConfigParser) parseClientSpec(spec string) (*Client, error) {
	// 匹配 host(options) 格式
	re := regexp.MustCompile(`^([^(]+)(?:\(([^)]*)\))?$`)
	matches := re.FindStringSubmatch(spec)

	if len(matches) < 2 {
		return nil, fmt.Errorf("无效的客户端规格: %s", spec)
	}

	client := &Client{
		Host:    strings.TrimSpace(matches[1]),
		Options: []string{},
	}

	// 解析选项
	if len(matches) > 2 && matches[2] != "" {
		opts := strings.Split(matches[2], ",")
		for _, opt := range opts {
			opt = strings.TrimSpace(opt)
			if opt != "" {
				client.Options = append(client.Options, opt)
			}
		}
	}

	return client, nil
}

// ParseClientOptions 从客户端选项解析导出选项
func (p *ConfigParser) ParseClientOptions(opts []string) ExportOptions {
	exportOpts := ExportOptions{
		Rw:           true,
		NoRootSquash: false,
		Async:        false,
		Secure:       false,
		SubtreeCheck: false,
	}

	for _, opt := range opts {
		switch strings.ToLower(opt) {
		case "ro":
			exportOpts.Ro = true
			exportOpts.Rw = false
		case "rw":
			exportOpts.Rw = true
			exportOpts.Ro = false
		case "no_root_squash":
			exportOpts.NoRootSquash = true
		case "root_squash":
			exportOpts.NoRootSquash = false
		case "async":
			exportOpts.Async = true
		case "sync":
			exportOpts.Async = false
		case "secure":
			exportOpts.Secure = true
		case "insecure":
			exportOpts.Secure = false
		case "subtree_check":
			exportOpts.SubtreeCheck = true
		case "no_subtree_check":
			exportOpts.SubtreeCheck = false
		}
	}

	return exportOpts
}

// WriteExportsFile 写入/etc/exports文件
func (p *ConfigParser) WriteExportsFile(path string, exports []*Export) error {
	file, err := os.Create(path)
	if err != nil {
		p.logger.Errorf("创建exports文件失败: %s - %v", path, err)
		return fmt.Errorf("创建文件失败: %w", err)
	}
	defer func() { _ = file.Close() }()

	// 写入文件头
	header := `# /etc/exports: the access control list for filesystems which may be exported
#               to NFS clients.  See exports(5).
# Generated by NAS-OS
`
	if _, err := file.WriteString(header); err != nil {
		return fmt.Errorf("写入文件头失败: %w", err)
	}

	// 写入每个导出配置
	for _, export := range exports {
		line := p.formatExportLine(export)
		if _, err := file.WriteString(line + "\n"); err != nil {
			return fmt.Errorf("写入导出配置失败: %w", err)
		}
	}

	p.logger.Infof("写入 %d 个导出配置到 %s", len(exports), path)
	return nil
}

// formatExportLine 格式化导出行
func (p *ConfigParser) formatExportLine(export *Export) string {
	var sb strings.Builder
	sb.WriteString(export.Path)

	for _, client := range export.Clients {
		sb.WriteString(" ")
		sb.WriteString(client.Host)

		// 合并导出选项和客户端特定选项
		opts := p.exportOptionsToString(&export.Options)
		if len(client.Options) > 0 {
			opts = opts + "," + strings.Join(client.Options, ",")
		}
		sb.WriteString("(" + opts + ")")
	}

	// 如果没有客户端，添加默认允许所有
	if len(export.Clients) == 0 {
		opts := p.exportOptionsToString(&export.Options)
		sb.WriteString(" *(" + opts + ")")
	}

	return sb.String()
}

// exportOptionsToString 将导出选项转换为字符串
func (p *ConfigParser) exportOptionsToString(opts *ExportOptions) string {
	var parts []string

	if opts.Ro {
		parts = append(parts, "ro")
	} else {
		parts = append(parts, "rw")
	}

	if opts.NoRootSquash {
		parts = append(parts, "no_root_squash")
	} else {
		parts = append(parts, "root_squash")
	}

	if opts.Async {
		parts = append(parts, "async")
	} else {
		parts = append(parts, "sync")
	}

	if opts.Secure {
		parts = append(parts, "secure")
	}

	if opts.SubtreeCheck {
		parts = append(parts, "subtree_check")
	} else {
		parts = append(parts, "no_subtree_check")
	}

	return strings.Join(parts, ",")
}

// ParseFSID 从选项中解析FSID
func (p *ConfigParser) ParseFSID(opts []string) (int, error) {
	for _, opt := range opts {
		if strings.HasPrefix(opt, "fsid=") {
			fsidStr := strings.TrimPrefix(opt, "fsid=")
			fsid, err := strconv.Atoi(fsidStr)
			if err != nil {
				return 0, fmt.Errorf("无效的fsid值: %s", fsidStr)
			}
			return fsid, nil
		}
	}
	return 0, nil // 默认0表示自动分配
}

// ValidateExportsPath 验证导出路径
func (p *ConfigParser) ValidateExportsPath(path string) error {
	// 检查路径是否是绝对路径
	if !filepath.IsAbs(path) {
		return fmt.Errorf("路径必须是绝对路径")
	}

	// 检查路径是否存在
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			// 路径不存在，将会创建
			return nil
		}
		return fmt.Errorf("无法访问路径: %w", err)
	}

	// 检查是否是目录
	if !info.IsDir() {
		return fmt.Errorf("路径必须是目录")
	}

	return nil
}

// ValidateHost 验证主机规格
func (p *ConfigParser) ValidateHost(host string) error {
	if host == "" {
		return fmt.Errorf("主机不能为空")
	}

	// 支持的格式:
	// - * (所有主机)
	// - hostname (主机名)
	// - 192.168.1.1 (IP地址)
	// - 192.168.1.0/24 (CIDR)
	// - 192.168.1.0/255.255.255.0 (网络掩码)
	// - @netgroup (NIS网络组)

	if host == "*" {
		return nil
	}

	if strings.HasPrefix(host, "@") {
		// NIS网络组
		return nil
	}

	// 简单验证IP地址或主机名格式
	// 这里不做严格验证，让NFS服务器处理无效输入
	return nil
}

// MergeExports 合并导出配置
func (p *ConfigParser) MergeExports(existing, newExports []*Export) []*Export {
	exportMap := make(map[string]*Export)

	// 先添加现有的
	for _, e := range existing {
		exportMap[e.Path] = e
	}

	// 用新的覆盖
	for _, e := range newExports {
		exportMap[e.Path] = e
	}

	// 转换为切片
	result := make([]*Export, 0, len(exportMap))
	for _, e := range exportMap {
		result = append(result, e)
	}

	return result
}
