package application

import "nas-os/internal/arch"

var moduleCatalog = map[string]arch.ModuleTier{
	moduleIdentity: arch.ModuleTierCore,
	moduleStorage:  arch.ModuleTierCore,
	moduleNetwork:  arch.ModuleTierCore,
	moduleSharing:  arch.ModuleTierCore,
	moduleSystem:   arch.ModuleTierCore,

	"acl":            arch.ModuleTierExtension,
	"acme":           arch.ModuleTierLab,
	"activebackup":   arch.ModuleTierLab,
	"activeprotect":  arch.ModuleTierExtension,
	"agentworkflow":  arch.ModuleTierExtension,
	"ai":             arch.ModuleTierExtension,
	"aiguardrails":   arch.ModuleTierExtension,
	"alerting":       arch.ModuleTierLab,
	"compliancescan": arch.ModuleTierExtension,
	"container":      arch.ModuleTierExtension,
	"deployorch":     arch.ModuleTierExtension,
	"download":       arch.ModuleTierLab,
	"netdiag":        arch.ModuleTierExtension,
	"reports":        arch.ModuleTierLab,
	"selfheal":       arch.ModuleTierLab,
	"smartpricing":   arch.ModuleTierLab,
	"voicehub":       arch.ModuleTierExtension,
	"ztna":           arch.ModuleTierLab,

	"benchmarkpro":       arch.ModuleTierLab,
	"blockdedup2":        arch.ModuleTierLab,
	"brandinsight":       arch.ModuleTierLab,
	"cinemarec":          arch.ModuleTierLab,
	"cloudsync2":         arch.ModuleTierLab,
	"containerpro":       arch.ModuleTierLab,
	"costbenchmark":      arch.ModuleTierLab,
	"datasovereignty2":   arch.ModuleTierLab,
	"digitalassetvault":  arch.ModuleTierLab,
	"draid2":             arch.ModuleTierLab,
	"familyactivityhub":  arch.ModuleTierLab,
	"featurematrix":      arch.ModuleTierLab,
	"filetimemachine2":   arch.ModuleTierLab,
	"forensics2":         arch.ModuleTierLab,
	"guidedalert":        arch.ModuleTierLab,
	"guidedalerts":       arch.ModuleTierLab,
	"iotedgegateway":     arch.ModuleTierLab,
	"netshield":          arch.ModuleTierLab,
	"posterwallpro":      arch.ModuleTierLab,
	"releasemanager":     arch.ModuleTierLab,
	"resmonpro":          arch.ModuleTierLab,
	"safeaccess":         arch.ModuleTierLab,
	"smartalert":         arch.ModuleTierLab,
	"snapviz":            arch.ModuleTierLab,
	"smarthomehubpro":    arch.ModuleTierLab,
	"smartthermal2":      arch.ModuleTierLab,
	"storagecostpredict": arch.ModuleTierLab,
	"tcodash":            arch.ModuleTierLab,
	"themepro":           arch.ModuleTierLab,
	"truecloudbk":        arch.ModuleTierLab,
	"updatedirector":     arch.ModuleTierLab,

	// demoted: smart* pseudo-core → lab
	"smartrecipe":        arch.ModuleTierLab,
	"smartcam":           arch.ModuleTierLab,
	"smartpowerschedule": arch.ModuleTierLab,
	"smartwearleveling":  arch.ModuleTierLab,
	"smartsleep":         arch.ModuleTierLab,
	"smartredundancy":    arch.ModuleTierLab,
	"smartlink":          arch.ModuleTierLab,
	"smartlifebackup":    arch.ModuleTierLab,
	"smartappcurator":    arch.ModuleTierLab,
	"smartresource":      arch.ModuleTierLab,
	"smartrecycle":       arch.ModuleTierLab,
	"smartrebuild":       arch.ModuleTierLab,
	"smartinsight":       arch.ModuleTierLab,
	"smartlifecycle":     arch.ModuleTierLab,

	// demoted: carbon/energy duplicates → lab
	"carbonaware":     arch.ModuleTierLab,
	"carbonfootprint": arch.ModuleTierLab,
	"carbontracker":   arch.ModuleTierLab,
	"smartcarbon":     arch.ModuleTierLab,
	"energydashboard": arch.ModuleTierLab,
	"energycost":      arch.ModuleTierLab,
	"energymanager":   arch.ModuleTierLab,

	// demoted: budget/finance duplicates → lab
	"budgetalert":    arch.ModuleTierLab,
	"budgetforecast": arch.ModuleTierLab,
	"budgetmgr":      arch.ModuleTierLab,
	"budgetplan":     arch.ModuleTierLab,
	"smartbudget":    arch.ModuleTierLab,
	"familyfinance":  arch.ModuleTierLab,

	// demoted: quantum pseudo-core → lab
	"quantumcrypto":     arch.ModuleTierLab,
	"quantumsafe":       arch.ModuleTierLab,
	"quantumsafevault":  arch.ModuleTierLab,
	"quantumsecurecomm": arch.ModuleTierLab,

	// demoted: duplicate AI modules → lab
	"aiagentorch":        arch.ModuleTierLab,
	"aianalyzer":         arch.ModuleTierLab,
	"aiassistant":        arch.ModuleTierLab,
	"aichatbot":          arch.ModuleTierLab,
	"aicodeassist":       arch.ModuleTierLab,
	"aiconsole":          arch.ModuleTierLab,
	"aiconttag":          arch.ModuleTierLab,
	"aidatadedup":        arch.ModuleTierLab,
	"aidatamasking":      arch.ModuleTierLab,
	"aidefrag":           arch.ModuleTierLab,
	"aideidentification": arch.ModuleTierLab,
	"aifilearchive":      arch.ModuleTierLab,
	"ailoganalyzer":      arch.ModuleTierLab,
	"aiops":              arch.ModuleTierLab,
	"aiplatform":         arch.ModuleTierLab,
	"aisysadmin":         arch.ModuleTierLab,
	"aitaskagent":        arch.ModuleTierLab,
	"aitokenmeter":       arch.ModuleTierLab,
	"aitraffic":          arch.ModuleTierLab,
	"aitranscription":    arch.ModuleTierLab,
	"aivideounderstand":  arch.ModuleTierLab,
	"aiworkflow":         arch.ModuleTierLab,
	"aiwriter":           arch.ModuleTierLab,
	"airplay":            arch.ModuleTierLab,

	// demoted: cost/billing/budget/tco/cloud duplicates → lab
	"cloudbillfc":     arch.ModuleTierLab,
	"cloudbilling":    arch.ModuleTierLab,
	"cloudfederation": arch.ModuleTierLab,
	"cloudfuse":       arch.ModuleTierLab,
	"cloudportal":     arch.ModuleTierLab,
	"cloudsyncmgr":    arch.ModuleTierLab,
	"cloudui":         arch.ModuleTierLab,
	"cloudbackupsync": arch.ModuleTierLab,
	"cloudmount":      arch.ModuleTierLab,
	"cloudconnect":    arch.ModuleTierLab,
	"cloudbackup":     arch.ModuleTierLab,
	"costdashboard":   arch.ModuleTierLab,
	"costforecast":    arch.ModuleTierLab,
	"costgovernance":  arch.ModuleTierLab,
	"costpredict":     arch.ModuleTierLab,
	"costanalyzer":    arch.ModuleTierLab,
	"tcocalc":         arch.ModuleTierLab,
	"tcodashboard":    arch.ModuleTierLab,
	"tcoshield":       arch.ModuleTierLab,
	"billing":         arch.ModuleTierLab,
	"budget":          arch.ModuleTierLab,
	"cost":            arch.ModuleTierLab,

	// demoted wave v3.22.0: file/storage/network/security/collab/ops pseudo-core → lab
	"acmemanager":         arch.ModuleTierLab,
	"activedirectory":     arch.ModuleTierLab,
	"activeinsight":       arch.ModuleTierLab,
	"activityfeed":        arch.ModuleTierLab,
	"adaptivetwofa":       arch.ModuleTierLab,
	"adminprivilege":      arch.ModuleTierLab,
	"album":               arch.ModuleTierLab,
	"analytics":           arch.ModuleTierLab,
	"antivirus":           arch.ModuleTierLab,
	"apilevelmeter":       arch.ModuleTierLab,
	"apimigrator":         arch.ModuleTierLab,
	"apiproxy":            arch.ModuleTierLab,
	"apisignverify":       arch.ModuleTierLab,
	"app":                 arch.ModuleTierLab,
	"appreview":           arch.ModuleTierLab,
	"appstore":            arch.ModuleTierLab,
	"armadapter":          arch.ModuleTierLab,
	"assetmgr":            arch.ModuleTierLab,
	"assetvaluator":       arch.ModuleTierLab,
	"audit":               arch.ModuleTierLab,
	"automation":          arch.ModuleTierLab,
	"batchrename":         arch.ModuleTierLab,
	"bitrotheal":          arch.ModuleTierLab,
	"bluetoothprovision":  arch.ModuleTierLab,
	"bootrepair":          arch.ModuleTierLab,
	"branding":            arch.ModuleTierLab,
	"brtprefetch":         arch.ModuleTierLab,
	"btrfs":               arch.ModuleTierLab,
	"cachewarm":           arch.ModuleTierLab,
	"calendar":            arch.ModuleTierLab,
	"cdp":                 arch.ModuleTierLab,
	"chat":                arch.ModuleTierLab,
	"clientthumb":         arch.ModuleTierLab,
	"clipboard":           arch.ModuleTierLab,
	"cms":                 arch.ModuleTierLab,
	"collaboration":       arch.ModuleTierLab,
	"compliance":          arch.ModuleTierLab,
	"complreport":         arch.ModuleTierLab,
	"composeinclude":      arch.ModuleTierLab,
	"composevisual":       arch.ModuleTierLab,
	"configdrift":         arch.ModuleTierLab,
	"connect":             arch.ModuleTierLab,
	"consensus":           arch.ModuleTierLab,
	"contacts":            arch.ModuleTierLab,
	"containwatch":        arch.ModuleTierLab,
	"contentai":           arch.ModuleTierLab,
	"contentseo":          arch.ModuleTierLab,
	"contentworkflow":     arch.ModuleTierLab,
	"cron":                arch.ModuleTierLab,
	"crossdevclipboard":   arch.ModuleTierLab,
	"crossnasreplication": arch.ModuleTierLab,
	"crossplatformsync":   arch.ModuleTierLab,
	"customdash":          arch.ModuleTierLab,
	"cxlmempool":          arch.ModuleTierLab,
	"cyberposture":        arch.ModuleTierLab,
	"dam":                 arch.ModuleTierLab,
	"datagovernance":      arch.ModuleTierLab,
	"datamigration":       arch.ModuleTierLab,
	"datasettier":         arch.ModuleTierLab,
	"datasovereignty":     arch.ModuleTierLab,
	"dedupadvisor":        arch.ModuleTierLab,
	"desktopmanager":      arch.ModuleTierLab,
	"diagnostics":         arch.ModuleTierLab,
	"digitalsignage":      arch.ModuleTierLab,
	"digitaltwin":         arch.ModuleTierLab,
	"directplay":          arch.ModuleTierLab,
	"diskhealth":          arch.ModuleTierLab,
	"distScheduler":       arch.ModuleTierLab,
	"distributedtask":     arch.ModuleTierLab,
	"dlpengine":           arch.ModuleTierLab,
	"dockercompose":       arch.ModuleTierLab,
	"dockermanager":       arch.ModuleTierLab,
	"docmanager":          arch.ModuleTierLab,
	"docprocessor":        arch.ModuleTierLab,
	"docworkspace":        arch.ModuleTierLab,
	"domainsync":          arch.ModuleTierLab,
	"downloadstation":     arch.ModuleTierLab,
	"dpdkaccel":           arch.ModuleTierLab,
	"draid":               arch.ModuleTierLab,
	"drive":               arch.ModuleTierLab,
	"driveinsight":        arch.ModuleTierLab,
	"drivemigration":      arch.ModuleTierLab,
	"edgegateway":         arch.ModuleTierLab,
	"enclosure":           arch.ModuleTierLab,
	"encryption":          arch.ModuleTierLab,
	"esignature":          arch.ModuleTierLab,
	"fancurve":            arch.ModuleTierLab,
	"fastdedup":           arch.ModuleTierLab,
	"fecconfig":           arch.ModuleTierLab,
	"federatednas":        arch.ModuleTierLab,
	"fido2":               arch.ModuleTierLab,
	"fileactivity":        arch.ModuleTierLab,
	"fileactivitywatcher": arch.ModuleTierLab,
	"filecache":           arch.ModuleTierLab,
	"filededup":           arch.ModuleTierLab,
	"fileinsights":        arch.ModuleTierLab,
	"fileintegrity":       arch.ModuleTierLab,
	"filelifecycle":       arch.ModuleTierLab,
	"filelock":            arch.ModuleTierLab,
	"filemanager":         arch.ModuleTierLab,
	"filepreview":         arch.ModuleTierLab,
	"filerequest":         arch.ModuleTierLab,
	"filesharing":         arch.ModuleTierLab,
	"filesyncclient":      arch.ModuleTierLab,
	"filesynchub":         arch.ModuleTierLab,
	"filetagger":          arch.ModuleTierLab,
	"filetimeline":        arch.ModuleTierLab,
	"filetimemachine":     arch.ModuleTierLab,
	"fileversion":         arch.ModuleTierLab,
	"filewatcher":         arch.ModuleTierLab,
	"fips":                arch.ModuleTierLab,
	"fipsvault":           arch.ModuleTierLab,
	"firewall":            arch.ModuleTierLab,
	"forensics":           arch.ModuleTierLab,
	"freeipa":             arch.ModuleTierLab,
	"fworchestrator":      arch.ModuleTierLab,
	"gateway":             arch.ModuleTierLab,
	"gdprscanner":         arch.ModuleTierLab,
	"geoipfirewall":       arch.ModuleTierLab,
	"hdddedup":            arch.ModuleTierLab,
	"hwcompat":            arch.ModuleTierLab,
	"hybridpool":          arch.ModuleTierLab,
	"hybridpoolmgr":       arch.ModuleTierLab,
	"immusnap":            arch.ModuleTierLab,
	"inlinededup":         arch.ModuleTierLab,
	"integrityverifier":   arch.ModuleTierLab,
	"ipv6net":             arch.ModuleTierLab,
	"iscsiblockclone":     arch.ModuleTierLab,
	"iscsifc":             arch.ModuleTierLab,
	"iscsitgtoffload":     arch.ModuleTierLab,
	"jsonrpc":             arch.ModuleTierLab,
	"kanban":              arch.ModuleTierLab,
	"kanbanboard":         arch.ModuleTierLab,
	"kerberos":            arch.ModuleTierLab,
	"kmip":                arch.ModuleTierLab,
	"kmipclient":          arch.ModuleTierLab,
	"knowledgebase":       arch.ModuleTierLab,
	"knowledgemap":        arch.ModuleTierLab,
	"ldap":                arch.ModuleTierLab,
	"linkaggbondadvisor":  arch.ModuleTierLab,
	"loadbalancer":        arch.ModuleTierLab,
	"localchat":           arch.ModuleTierLab,
	"localknowledgebase":  arch.ModuleTierLab,
	"mailserver":          arch.ModuleTierLab,
	"media":               arch.ModuleTierLab,
	"mpiofc":              arch.ModuleTierLab,
	"nasdiscovery":        arch.ModuleTierLab,
	"netdatawidget":       arch.ModuleTierLab,
	"notes":               arch.ModuleTierLab,
	"nvmeof":              arch.ModuleTierLab,
	"nvmeofenhanced":      arch.ModuleTierLab,
	"securep2pshare":      arch.ModuleTierLab,
	"sharelinks":          arch.ModuleTierLab,
	"ssdcache":            arch.ModuleTierLab,
	"storagemigration":    arch.ModuleTierLab,
	"storagetiering":      arch.ModuleTierLab,
	"teamworkspace":       arch.ModuleTierLab,
	"trafficclassifier":   arch.ModuleTierLab,
	"usbreset":            arch.ModuleTierLab,
}

// ModuleTierFor 返回模块在当前收敛目录中的层级。
// 未知名称默认 Lab（实验/未编目），不得伪装成 Core 或已接线的 Extension 产品面。
func ModuleTierFor(name string) arch.ModuleTier {
	if tier, ok := moduleCatalog[name]; ok {
		return tier
	}
	return arch.ModuleTierLab
}

// ModuleCatalogSnapshot 返回当前架构收敛视角下的模块清单。
// 仅 Core 允许进入进程生命周期主图；编目中的 Extension 需配置 modules.extensions 才会加载。
func ModuleCatalogSnapshot() map[string]arch.ModuleTier {
	catalog := make(map[string]arch.ModuleTier, len(moduleCatalog))
	for name, tier := range moduleCatalog {
		catalog[name] = tier
	}
	return catalog
}
