package application

import (
	"os"
	"testing"

	"nas-os/internal/arch"
)

func TestModuleCatalogSnapshotCoreModules(t *testing.T) {
	catalog := ModuleCatalogSnapshot()
	for _, name := range []string{moduleIdentity, moduleStorage, moduleNetwork, moduleSharing, moduleSystem} {
		if got := catalog[name]; got != arch.ModuleTierCore {
			t.Fatalf("catalog[%s] = %q, want %q", name, got, arch.ModuleTierCore)
		}
	}
}

func TestModuleCatalogSnapshotDemotesPseudoCoreModules(t *testing.T) {
	catalog := ModuleCatalogSnapshot()
	cases := map[string]arch.ModuleTier{
		"activeprotect":     arch.ModuleTierExtension,
		"agentworkflow":     arch.ModuleTierExtension,
		"benchmarkpro":      arch.ModuleTierLab,
		"blockdedup2":       arch.ModuleTierLab,
		"brandinsight":      arch.ModuleTierLab,
		"cinemarec":         arch.ModuleTierLab,
		"cloudsync2":        arch.ModuleTierLab,
		"containerpro":      arch.ModuleTierLab,
		"compliancescan":    arch.ModuleTierExtension,
		"datasovereignty2":  arch.ModuleTierLab,
		"deployorch":        arch.ModuleTierExtension,
		"digitalassetvault": arch.ModuleTierLab,
		"familyactivityhub": arch.ModuleTierLab,
		"filetimemachine2":  arch.ModuleTierLab,
		"guidedalert":       arch.ModuleTierLab,
		"guidedalerts":      arch.ModuleTierLab,
		"iotedgegateway":    arch.ModuleTierLab,
		"netdiag":           arch.ModuleTierExtension,
		"resmonpro":         arch.ModuleTierLab,
		"snapviz":           arch.ModuleTierLab,
		"smartalert":        arch.ModuleTierLab,
		"smarthomehubpro":   arch.ModuleTierLab,
		"smartthermal2":     arch.ModuleTierLab,
		"tcodash":           arch.ModuleTierLab,
		"themepro":          arch.ModuleTierLab,
		"updatedirector":    arch.ModuleTierLab,
		"acme":              arch.ModuleTierLab,
		"activebackup":      arch.ModuleTierLab,
		"alerting":          arch.ModuleTierLab,
		"selfheal":          arch.ModuleTierLab,
		"ztna":              arch.ModuleTierLab,
		"reports":           arch.ModuleTierLab,
		"smartpricing":      arch.ModuleTierLab,
		"filemanager":       arch.ModuleTierLab,
		"filetimemachine":   arch.ModuleTierLab,
		"storagetiering":    arch.ModuleTierLab,
		"nvmeof":            arch.ModuleTierLab,
		"hybridpool":        arch.ModuleTierLab,
		"connect":           arch.ModuleTierLab,
		"firewall":          arch.ModuleTierLab,
		"ldap":              arch.ModuleTierLab,
		"fido2":             arch.ModuleTierLab,
		"media":             arch.ModuleTierLab,
		"downloadstation":   arch.ModuleTierLab,
		"collaboration":     arch.ModuleTierLab,
		"automation":        arch.ModuleTierLab,
		"dockercompose":     arch.ModuleTierLab,
		"appstore":          arch.ModuleTierLab,
		"ssdcache":          arch.ModuleTierLab,
		"nasdiscovery":      arch.ModuleTierLab,
	}
	for name, want := range cases {
		if got := catalog[name]; got != want {
			t.Fatalf("catalog[%s] = %q, want %q", name, got, want)
		}
	}
}

func TestModuleTierForDefaultsUnknownModulesToExtension(t *testing.T) {
	if got := ModuleTierFor("totally-new-module"); got != arch.ModuleTierExtension {
		t.Fatalf("ModuleTierFor(unknown) = %q, want %q", got, arch.ModuleTierExtension)
	}
}

func TestModuleCatalogSnapshotReturnsCopy(t *testing.T) {
	catalog := ModuleCatalogSnapshot()
	catalog[moduleIdentity] = arch.ModuleTierLab
	if got := ModuleTierFor(moduleIdentity); got != arch.ModuleTierCore {
		t.Fatalf("ModuleTierFor(%s) mutated to %q, want %q", moduleIdentity, got, arch.ModuleTierCore)
	}
}

func TestTieredModulesLiveUnderTieredNamespaces(t *testing.T) {
	cases := map[string]string{
		"/home/mrafter/nas-os/internal/lab/benchmarkpro":          "benchmarkpro should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/blockdedup2":           "blockdedup2 should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/brandinsight":          "brandinsight should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudsync2":            "cloudsync2 should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/containerpro":          "containerpro should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cinemarec":             "cinemarec should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/releasemanager":        "releasemanager should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/resmonpro":             "resmonpro should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aimediatag":            "aimediatag should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/costbenchmark":         "costbenchmark should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/datasovereignty2":      "datasovereignty2 should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/digitalassetvault":     "digitalassetvault should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/draid2":                "draid2 should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/featurematrix":         "featurematrix should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/familyactivityhub":     "familyactivityhub should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filetimemachine2":      "filetimemachine2 should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/forensics2":            "forensics2 should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/iotedgegateway":        "iotedgegateway should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/netshield":             "netshield should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/posterwallpro":         "posterwallpro should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/safeaccess":            "safeaccess should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/snapviz":               "snapviz should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/smartthermal2":         "smartthermal2 should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/smarthomehubpro":       "smarthomehubpro should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/storagecostpredict":    "storagecostpredict should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/tcodash":               "tcodash should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/themepro":              "themepro should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/truecloudbk":           "truecloudbk should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/updatedirector":        "updatedirector should live under internal/lab",
		"/home/mrafter/nas-os/internal/extensions/activeprotect":  "activeprotect should live under internal/extensions",
		"/home/mrafter/nas-os/internal/extensions/agentworkflow":  "agentworkflow should live under internal/extensions",
		"/home/mrafter/nas-os/internal/extensions/aiguardrails":   "aiguardrails should live under internal/extensions",
		"/home/mrafter/nas-os/internal/extensions/compliancescan": "compliancescan should live under internal/extensions",
		"/home/mrafter/nas-os/internal/extensions/deployorch":     "deployorch should live under internal/extensions",
		"/home/mrafter/nas-os/internal/extensions/netdiag":        "netdiag should live under internal/extensions",
		"/home/mrafter/nas-os/internal/extensions/voicehub":       "voicehub should live under internal/extensions",
		"/home/mrafter/nas-os/internal/lab/aiagentorch":           "aiagentorch should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aianalyzer":            "aianalyzer should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aiassistant":           "aiassistant should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aichatbot":             "aichatbot should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aicodeassist":          "aicodeassist should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aiconsole":             "aiconsole should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aiconttag":             "aiconttag should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aidatadedup":           "aidatadedup should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aidatamasking":         "aidatamasking should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aidefrag":              "aidefrag should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aideidentification":    "aideidentification should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aifilearchive":         "aifilearchive should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/ailoganalyzer":         "ailoganalyzer should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aiops":                 "aiops should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aiplatform":            "aiplatform should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/airplay":               "airplay should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aisysadmin":            "aisysadmin should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aitaskagent":           "aitaskagent should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aitokenmeter":          "aitokenmeter should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aitraffic":             "aitraffic should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aitranscription":       "aitranscription should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aivideounderstand":     "aivideounderstand should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aiworkflow":            "aiworkflow should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/aiwriter":              "aiwriter should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/billing":               "billing should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/budget":                "budget should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudbackup":           "cloudbackup should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudbackupsync":       "cloudbackupsync should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudbillfc":           "cloudbillfc should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudbilling":          "cloudbilling should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudconnect":          "cloudconnect should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudfederation":       "cloudfederation should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudfuse":             "cloudfuse should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudmount":            "cloudmount should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudportal":           "cloudportal should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudsyncmgr":          "cloudsyncmgr should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cloudui":               "cloudui should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cost":                  "cost should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/costanalyzer":          "costanalyzer should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/costdashboard":         "costdashboard should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/costforecast":          "costforecast should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/costgovernance":        "costgovernance should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/costpredict":           "costpredict should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/quantumcrypto":         "quantumcrypto should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/quantumsafe":           "quantumsafe should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/quantumsafevault":      "quantumsafevault should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/quantumsecurecomm":     "quantumsecurecomm should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/tcocalc":               "tcocalc should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/tcodashboard":          "tcodashboard should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/tcoshield":             "tcoshield should live under internal/lab",
		// v3.22.0 demotion wave path locks
		"/home/mrafter/nas-os/internal/lab/acme":                "acme should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/acmemanager":         "acmemanager should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/activedirectory":     "activedirectory should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/activeinsight":       "activeinsight should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/activityfeed":        "activityfeed should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/adaptivetwofa":       "adaptivetwofa should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/adminprivilege":      "adminprivilege should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/album":               "album should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/alerting":            "alerting should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/analytics":           "analytics should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/antivirus":           "antivirus should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/apilevelmeter":       "apilevelmeter should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/apimigrator":         "apimigrator should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/apiproxy":            "apiproxy should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/apisignverify":       "apisignverify should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/app":                 "app should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/appreview":           "appreview should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/appstore":            "appstore should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/armadapter":          "armadapter should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/assetmgr":            "assetmgr should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/assetvaluator":       "assetvaluator should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/audit":               "audit should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/automation":          "automation should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/batchrename":         "batchrename should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/bitrotheal":          "bitrotheal should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/bluetoothprovision":  "bluetoothprovision should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/bootrepair":          "bootrepair should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/branding":            "branding should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/brtprefetch":         "brtprefetch should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/btrfs":               "btrfs should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cachewarm":           "cachewarm should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/calendar":            "calendar should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cdp":                 "cdp should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/chat":                "chat should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/clientthumb":         "clientthumb should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/clipboard":           "clipboard should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cms":                 "cms should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/collaboration":       "collaboration should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/compliance":          "compliance should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/complreport":         "complreport should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/composeinclude":      "composeinclude should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/composevisual":       "composevisual should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/configdrift":         "configdrift should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/connect":             "connect should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/consensus":           "consensus should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/contacts":            "contacts should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/containwatch":        "containwatch should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/contentai":           "contentai should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/contentseo":          "contentseo should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/contentworkflow":     "contentworkflow should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cron":                "cron should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/crossdevclipboard":   "crossdevclipboard should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/crossnasreplication": "crossnasreplication should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/crossplatformsync":   "crossplatformsync should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/customdash":          "customdash should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cxlmempool":          "cxlmempool should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/cyberposture":        "cyberposture should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/dam":                 "dam should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/datagovernance":      "datagovernance should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/datamigration":       "datamigration should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/datasettier":         "datasettier should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/dedupadvisor":        "dedupadvisor should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/desktopmanager":      "desktopmanager should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/diagnostics":         "diagnostics should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/digitalsignage":      "digitalsignage should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/digitaltwin":         "digitaltwin should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/directplay":          "directplay should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/diskhealth":          "diskhealth should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/distScheduler":       "distScheduler should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/distributedtask":     "distributedtask should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/dlpengine":           "dlpengine should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/dockercompose":       "dockercompose should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/dockermanager":       "dockermanager should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/docmanager":          "docmanager should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/docprocessor":        "docprocessor should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/docworkspace":        "docworkspace should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/domainsync":          "domainsync should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/downloadstation":     "downloadstation should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/dpdkaccel":           "dpdkaccel should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/drive":               "drive should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/driveinsight":        "driveinsight should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/drivemigration":      "drivemigration should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/edgegateway":         "edgegateway should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/enclosure":           "enclosure should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/encryption":          "encryption should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/esignature":          "esignature should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fancurve":            "fancurve should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fastdedup":           "fastdedup should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fecconfig":           "fecconfig should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/federatednas":        "federatednas should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fido2":               "fido2 should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fileactivity":        "fileactivity should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fileactivitywatcher": "fileactivitywatcher should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filecache":           "filecache should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filededup":           "filededup should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fileinsights":        "fileinsights should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fileintegrity":       "fileintegrity should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filelifecycle":       "filelifecycle should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filelock":            "filelock should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filemanager":         "filemanager should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filepreview":         "filepreview should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filerequest":         "filerequest should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filesharing":         "filesharing should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filesyncclient":      "filesyncclient should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filesynchub":         "filesynchub should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filetagger":          "filetagger should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filetimeline":        "filetimeline should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fileversion":         "fileversion should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/filewatcher":         "filewatcher should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fips":                "fips should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fipsvault":           "fipsvault should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/firewall":            "firewall should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/freeipa":             "freeipa should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/fworchestrator":      "fworchestrator should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/gateway":             "gateway should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/gdprscanner":         "gdprscanner should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/geoipfirewall":       "geoipfirewall should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/hdddedup":            "hdddedup should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/hwcompat":            "hwcompat should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/hybridpool":          "hybridpool should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/hybridpoolmgr":       "hybridpoolmgr should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/immusnap":            "immusnap should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/inlinededup":         "inlinededup should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/integrityverifier":   "integrityverifier should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/ipv6net":             "ipv6net should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/iscsiblockclone":     "iscsiblockclone should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/iscsifc":             "iscsifc should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/iscsitgtoffload":     "iscsitgtoffload should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/jsonrpc":             "jsonrpc should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/kanban":              "kanban should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/kanbanboard":         "kanbanboard should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/kerberos":            "kerberos should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/kmip":                "kmip should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/kmipclient":          "kmipclient should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/knowledgebase":       "knowledgebase should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/knowledgemap":        "knowledgemap should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/ldap":                "ldap should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/linkaggbondadvisor":  "linkaggbondadvisor should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/loadbalancer":        "loadbalancer should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/localchat":           "localchat should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/localknowledgebase":  "localknowledgebase should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/mailserver":          "mailserver should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/media":               "media should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/mpiofc":              "mpiofc should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/nasdiscovery":        "nasdiscovery should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/netdatawidget":       "netdatawidget should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/notes":               "notes should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/nvmeof":              "nvmeof should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/nvmeofenhanced":      "nvmeofenhanced should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/securep2pshare":      "securep2pshare should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/selfheal":            "selfheal should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/sharelinks":          "sharelinks should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/ssdcache":            "ssdcache should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/storagemigration":    "storagemigration should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/storagetiering":      "storagetiering should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/teamworkspace":       "teamworkspace should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/trafficclassifier":   "trafficclassifier should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/usbreset":            "usbreset should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/ztna":                "ztna should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/activebackup":        "activebackup should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/reports":             "reports should live under internal/lab",
		"/home/mrafter/nas-os/internal/lab/smartpricing":        "smartpricing should live under internal/lab",
	}
	for path, msg := range cases {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("%s: %v", msg, err)
		}
	}
}

func TestDeprecatedTopLevelTieredModulePathsAreGone(t *testing.T) {
	paths := map[string]string{
		"/home/mrafter/nas-os/internal/activeprotect":      "activeprotect should not remain at internal top level",
		"/home/mrafter/nas-os/internal/agentworkflow":      "agentworkflow should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiguardrails":       "aiguardrails should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aimediatag":         "aimediatag should not remain at internal top level",
		"/home/mrafter/nas-os/internal/benchmarkpro":       "benchmarkpro should not remain at internal top level",
		"/home/mrafter/nas-os/internal/blockdedup2":        "blockdedup2 should not remain at internal top level",
		"/home/mrafter/nas-os/internal/brandinsight":       "brandinsight should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudsync2":         "cloudsync2 should not remain at internal top level",
		"/home/mrafter/nas-os/internal/containerpro":       "containerpro should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cinemarec":          "cinemarec should not remain at internal top level",
		"/home/mrafter/nas-os/internal/compliancescan":     "compliancescan should not remain at internal top level",
		"/home/mrafter/nas-os/internal/costbenchmark":      "costbenchmark should not remain at internal top level",
		"/home/mrafter/nas-os/internal/datasovereignty2":   "datasovereignty2 should not remain at internal top level",
		"/home/mrafter/nas-os/internal/digitalassetvault":  "digitalassetvault should not remain at internal top level",
		"/home/mrafter/nas-os/internal/draid2":             "draid2 should not remain at internal top level",
		"/home/mrafter/nas-os/internal/featurematrix":      "featurematrix should not remain at internal top level",
		"/home/mrafter/nas-os/internal/familyactivityhub":  "familyactivityhub should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filetimemachine2":   "filetimemachine2 should not remain at internal top level",
		"/home/mrafter/nas-os/internal/forensics2":         "forensics2 should not remain at internal top level",
		"/home/mrafter/nas-os/internal/guidedalert":        "guidedalert should not remain at internal top level",
		"/home/mrafter/nas-os/internal/guidedalerts":       "guidedalerts should not remain at internal top level",
		"/home/mrafter/nas-os/internal/iotedgegateway":     "iotedgegateway should not remain at internal top level",
		"/home/mrafter/nas-os/internal/deployorch":         "deployorch should not remain at internal top level",
		"/home/mrafter/nas-os/internal/netdiag":            "netdiag should not remain at internal top level",
		"/home/mrafter/nas-os/internal/netshield":          "netshield should not remain at internal top level",
		"/home/mrafter/nas-os/internal/posterwallpro":      "posterwallpro should not remain at internal top level",
		"/home/mrafter/nas-os/internal/releasemanager":     "releasemanager should not remain at internal top level",
		"/home/mrafter/nas-os/internal/resmonpro":          "resmonpro should not remain at internal top level",
		"/home/mrafter/nas-os/internal/safeaccess":         "safeaccess should not remain at internal top level",
		"/home/mrafter/nas-os/internal/snapviz":            "snapviz should not remain at internal top level",
		"/home/mrafter/nas-os/internal/smartalert":         "smartalert should not remain at internal top level",
		"/home/mrafter/nas-os/internal/smartthermal2":      "smartthermal2 should not remain at internal top level",
		"/home/mrafter/nas-os/internal/smarthomehubpro":    "smarthomehubpro should not remain at internal top level",
		"/home/mrafter/nas-os/internal/storagecostpredict": "storagecostpredict should not remain at internal top level",
		"/home/mrafter/nas-os/internal/tcodash":            "tcodash should not remain at internal top level",
		"/home/mrafter/nas-os/internal/themepro":           "themepro should not remain at internal top level",
		"/home/mrafter/nas-os/internal/truecloudbk":        "truecloudbk should not remain at internal top level",
		"/home/mrafter/nas-os/internal/updatedirector":     "updatedirector should not remain at internal top level",
		"/home/mrafter/nas-os/internal/voicehub":           "voicehub should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiagentorch":        "aiagentorch should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aianalyzer":         "aianalyzer should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiassistant":        "aiassistant should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aichatbot":          "aichatbot should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aicodeassist":       "aicodeassist should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiconsole":          "aiconsole should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiconttag":          "aiconttag should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aidatadedup":        "aidatadedup should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aidatamasking":      "aidatamasking should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aidefrag":           "aidefrag should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aideidentification": "aideidentification should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aifilearchive":      "aifilearchive should not remain at internal top level",
		"/home/mrafter/nas-os/internal/ailoganalyzer":      "ailoganalyzer should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiops":              "aiops should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiplatform":         "aiplatform should not remain at internal top level",
		"/home/mrafter/nas-os/internal/airplay":            "airplay should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aisysadmin":         "aisysadmin should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aitaskagent":        "aitaskagent should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aitokenmeter":       "aitokenmeter should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aitraffic":          "aitraffic should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aitranscription":    "aitranscription should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aivideounderstand":  "aivideounderstand should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiworkflow":         "aiworkflow should not remain at internal top level",
		"/home/mrafter/nas-os/internal/aiwriter":           "aiwriter should not remain at internal top level",
		"/home/mrafter/nas-os/internal/billing":            "billing should not remain at internal top level",
		"/home/mrafter/nas-os/internal/budget":             "budget should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudbackup":        "cloudbackup should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudbackupsync":    "cloudbackupsync should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudbillfc":        "cloudbillfc should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudbilling":       "cloudbilling should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudconnect":       "cloudconnect should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudfederation":    "cloudfederation should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudfuse":          "cloudfuse should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudmount":         "cloudmount should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudportal":        "cloudportal should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudsyncmgr":       "cloudsyncmgr should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cloudui":            "cloudui should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cost":               "cost should not remain at internal top level",
		"/home/mrafter/nas-os/internal/costanalyzer":       "costanalyzer should not remain at internal top level",
		"/home/mrafter/nas-os/internal/costdashboard":      "costdashboard should not remain at internal top level",
		"/home/mrafter/nas-os/internal/costforecast":       "costforecast should not remain at internal top level",
		"/home/mrafter/nas-os/internal/costgovernance":     "costgovernance should not remain at internal top level",
		"/home/mrafter/nas-os/internal/costpredict":        "costpredict should not remain at internal top level",
		"/home/mrafter/nas-os/internal/quantumcrypto":      "quantumcrypto should not remain at internal top level",
		"/home/mrafter/nas-os/internal/quantumsafe":        "quantumsafe should not remain at internal top level",
		"/home/mrafter/nas-os/internal/quantumsafevault":   "quantumsafevault should not remain at internal top level",
		"/home/mrafter/nas-os/internal/quantumsecurecomm":  "quantumsecurecomm should not remain at internal top level",
		"/home/mrafter/nas-os/internal/tcocalc":            "tcocalc should not remain at internal top level",
		"/home/mrafter/nas-os/internal/tcodashboard":       "tcodashboard should not remain at internal top level",
		"/home/mrafter/nas-os/internal/tcoshield":          "tcoshield should not remain at internal top level",
		// v3.22.0 demotion wave: old top-level paths must stay gone
		"/home/mrafter/nas-os/internal/acme":                "acme should not remain at internal top level",
		"/home/mrafter/nas-os/internal/acmemanager":         "acmemanager should not remain at internal top level",
		"/home/mrafter/nas-os/internal/activedirectory":     "activedirectory should not remain at internal top level",
		"/home/mrafter/nas-os/internal/activeinsight":       "activeinsight should not remain at internal top level",
		"/home/mrafter/nas-os/internal/activityfeed":        "activityfeed should not remain at internal top level",
		"/home/mrafter/nas-os/internal/adaptivetwofa":       "adaptivetwofa should not remain at internal top level",
		"/home/mrafter/nas-os/internal/adminprivilege":      "adminprivilege should not remain at internal top level",
		"/home/mrafter/nas-os/internal/album":               "album should not remain at internal top level",
		"/home/mrafter/nas-os/internal/alerting":            "alerting should not remain at internal top level",
		"/home/mrafter/nas-os/internal/analytics":           "analytics should not remain at internal top level",
		"/home/mrafter/nas-os/internal/antivirus":           "antivirus should not remain at internal top level",
		"/home/mrafter/nas-os/internal/apilevelmeter":       "apilevelmeter should not remain at internal top level",
		"/home/mrafter/nas-os/internal/apimigrator":         "apimigrator should not remain at internal top level",
		"/home/mrafter/nas-os/internal/apiproxy":            "apiproxy should not remain at internal top level",
		"/home/mrafter/nas-os/internal/apisignverify":       "apisignverify should not remain at internal top level",
		"/home/mrafter/nas-os/internal/app":                 "app should not remain at internal top level",
		"/home/mrafter/nas-os/internal/appreview":           "appreview should not remain at internal top level",
		"/home/mrafter/nas-os/internal/appstore":            "appstore should not remain at internal top level",
		"/home/mrafter/nas-os/internal/armadapter":          "armadapter should not remain at internal top level",
		"/home/mrafter/nas-os/internal/assetmgr":            "assetmgr should not remain at internal top level",
		"/home/mrafter/nas-os/internal/assetvaluator":       "assetvaluator should not remain at internal top level",
		"/home/mrafter/nas-os/internal/audit":               "audit should not remain at internal top level",
		"/home/mrafter/nas-os/internal/automation":          "automation should not remain at internal top level",
		"/home/mrafter/nas-os/internal/batchrename":         "batchrename should not remain at internal top level",
		"/home/mrafter/nas-os/internal/bitrotheal":          "bitrotheal should not remain at internal top level",
		"/home/mrafter/nas-os/internal/bluetoothprovision":  "bluetoothprovision should not remain at internal top level",
		"/home/mrafter/nas-os/internal/bootrepair":          "bootrepair should not remain at internal top level",
		"/home/mrafter/nas-os/internal/branding":            "branding should not remain at internal top level",
		"/home/mrafter/nas-os/internal/brtprefetch":         "brtprefetch should not remain at internal top level",
		"/home/mrafter/nas-os/internal/btrfs":               "btrfs should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cachewarm":           "cachewarm should not remain at internal top level",
		"/home/mrafter/nas-os/internal/calendar":            "calendar should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cdp":                 "cdp should not remain at internal top level",
		"/home/mrafter/nas-os/internal/chat":                "chat should not remain at internal top level",
		"/home/mrafter/nas-os/internal/clientthumb":         "clientthumb should not remain at internal top level",
		"/home/mrafter/nas-os/internal/clipboard":           "clipboard should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cms":                 "cms should not remain at internal top level",
		"/home/mrafter/nas-os/internal/collaboration":       "collaboration should not remain at internal top level",
		"/home/mrafter/nas-os/internal/complreport":         "complreport should not remain at internal top level",
		"/home/mrafter/nas-os/internal/composeinclude":      "composeinclude should not remain at internal top level",
		"/home/mrafter/nas-os/internal/composevisual":       "composevisual should not remain at internal top level",
		"/home/mrafter/nas-os/internal/configdrift":         "configdrift should not remain at internal top level",
		"/home/mrafter/nas-os/internal/connect":             "connect should not remain at internal top level",
		"/home/mrafter/nas-os/internal/consensus":           "consensus should not remain at internal top level",
		"/home/mrafter/nas-os/internal/contacts":            "contacts should not remain at internal top level",
		"/home/mrafter/nas-os/internal/containwatch":        "containwatch should not remain at internal top level",
		"/home/mrafter/nas-os/internal/contentai":           "contentai should not remain at internal top level",
		"/home/mrafter/nas-os/internal/contentseo":          "contentseo should not remain at internal top level",
		"/home/mrafter/nas-os/internal/contentworkflow":     "contentworkflow should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cron":                "cron should not remain at internal top level",
		"/home/mrafter/nas-os/internal/crossdevclipboard":   "crossdevclipboard should not remain at internal top level",
		"/home/mrafter/nas-os/internal/crossnasreplication": "crossnasreplication should not remain at internal top level",
		"/home/mrafter/nas-os/internal/crossplatformsync":   "crossplatformsync should not remain at internal top level",
		"/home/mrafter/nas-os/internal/customdash":          "customdash should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cxlmempool":          "cxlmempool should not remain at internal top level",
		"/home/mrafter/nas-os/internal/cyberposture":        "cyberposture should not remain at internal top level",
		"/home/mrafter/nas-os/internal/dam":                 "dam should not remain at internal top level",
		"/home/mrafter/nas-os/internal/datagovernance":      "datagovernance should not remain at internal top level",
		"/home/mrafter/nas-os/internal/datamigration":       "datamigration should not remain at internal top level",
		"/home/mrafter/nas-os/internal/datasettier":         "datasettier should not remain at internal top level",
		"/home/mrafter/nas-os/internal/dedupadvisor":        "dedupadvisor should not remain at internal top level",
		"/home/mrafter/nas-os/internal/desktopmanager":      "desktopmanager should not remain at internal top level",
		"/home/mrafter/nas-os/internal/diagnostics":         "diagnostics should not remain at internal top level",
		"/home/mrafter/nas-os/internal/digitalsignage":      "digitalsignage should not remain at internal top level",
		"/home/mrafter/nas-os/internal/digitaltwin":         "digitaltwin should not remain at internal top level",
		"/home/mrafter/nas-os/internal/directplay":          "directplay should not remain at internal top level",
		"/home/mrafter/nas-os/internal/diskhealth":          "diskhealth should not remain at internal top level",
		"/home/mrafter/nas-os/internal/distScheduler":       "distScheduler should not remain at internal top level",
		"/home/mrafter/nas-os/internal/distributedtask":     "distributedtask should not remain at internal top level",
		"/home/mrafter/nas-os/internal/dlpengine":           "dlpengine should not remain at internal top level",
		"/home/mrafter/nas-os/internal/dockercompose":       "dockercompose should not remain at internal top level",
		"/home/mrafter/nas-os/internal/dockermanager":       "dockermanager should not remain at internal top level",
		"/home/mrafter/nas-os/internal/docmanager":          "docmanager should not remain at internal top level",
		"/home/mrafter/nas-os/internal/docprocessor":        "docprocessor should not remain at internal top level",
		"/home/mrafter/nas-os/internal/docworkspace":        "docworkspace should not remain at internal top level",
		"/home/mrafter/nas-os/internal/domainsync":          "domainsync should not remain at internal top level",
		"/home/mrafter/nas-os/internal/downloadstation":     "downloadstation should not remain at internal top level",
		"/home/mrafter/nas-os/internal/dpdkaccel":           "dpdkaccel should not remain at internal top level",
		"/home/mrafter/nas-os/internal/drive":               "drive should not remain at internal top level",
		"/home/mrafter/nas-os/internal/driveinsight":        "driveinsight should not remain at internal top level",
		"/home/mrafter/nas-os/internal/drivemigration":      "drivemigration should not remain at internal top level",
		"/home/mrafter/nas-os/internal/edgegateway":         "edgegateway should not remain at internal top level",
		"/home/mrafter/nas-os/internal/enclosure":           "enclosure should not remain at internal top level",
		"/home/mrafter/nas-os/internal/encryption":          "encryption should not remain at internal top level",
		"/home/mrafter/nas-os/internal/esignature":          "esignature should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fancurve":            "fancurve should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fastdedup":           "fastdedup should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fecconfig":           "fecconfig should not remain at internal top level",
		"/home/mrafter/nas-os/internal/federatednas":        "federatednas should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fido2":               "fido2 should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fileactivity":        "fileactivity should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fileactivitywatcher": "fileactivitywatcher should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filecache":           "filecache should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filededup":           "filededup should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fileinsights":        "fileinsights should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fileintegrity":       "fileintegrity should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filelifecycle":       "filelifecycle should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filelock":            "filelock should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filemanager":         "filemanager should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filepreview":         "filepreview should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filerequest":         "filerequest should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filesharing":         "filesharing should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filesyncclient":      "filesyncclient should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filesynchub":         "filesynchub should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filetagger":          "filetagger should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filetimeline":        "filetimeline should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fileversion":         "fileversion should not remain at internal top level",
		"/home/mrafter/nas-os/internal/filewatcher":         "filewatcher should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fips":                "fips should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fipsvault":           "fipsvault should not remain at internal top level",
		"/home/mrafter/nas-os/internal/firewall":            "firewall should not remain at internal top level",
		"/home/mrafter/nas-os/internal/freeipa":             "freeipa should not remain at internal top level",
		"/home/mrafter/nas-os/internal/fworchestrator":      "fworchestrator should not remain at internal top level",
		"/home/mrafter/nas-os/internal/gateway":             "gateway should not remain at internal top level",
		"/home/mrafter/nas-os/internal/gdprscanner":         "gdprscanner should not remain at internal top level",
		"/home/mrafter/nas-os/internal/geoipfirewall":       "geoipfirewall should not remain at internal top level",
		"/home/mrafter/nas-os/internal/hdddedup":            "hdddedup should not remain at internal top level",
		"/home/mrafter/nas-os/internal/hwcompat":            "hwcompat should not remain at internal top level",
		"/home/mrafter/nas-os/internal/hybridpool":          "hybridpool should not remain at internal top level",
		"/home/mrafter/nas-os/internal/hybridpoolmgr":       "hybridpoolmgr should not remain at internal top level",
		"/home/mrafter/nas-os/internal/immusnap":            "immusnap should not remain at internal top level",
		"/home/mrafter/nas-os/internal/inlinededup":         "inlinededup should not remain at internal top level",
		"/home/mrafter/nas-os/internal/integrityverifier":   "integrityverifier should not remain at internal top level",
		"/home/mrafter/nas-os/internal/ipv6net":             "ipv6net should not remain at internal top level",
		"/home/mrafter/nas-os/internal/iscsiblockclone":     "iscsiblockclone should not remain at internal top level",
		"/home/mrafter/nas-os/internal/iscsifc":             "iscsifc should not remain at internal top level",
		"/home/mrafter/nas-os/internal/iscsitgtoffload":     "iscsitgtoffload should not remain at internal top level",
		"/home/mrafter/nas-os/internal/jsonrpc":             "jsonrpc should not remain at internal top level",
		"/home/mrafter/nas-os/internal/kanban":              "kanban should not remain at internal top level",
		"/home/mrafter/nas-os/internal/kanbanboard":         "kanbanboard should not remain at internal top level",
		"/home/mrafter/nas-os/internal/kerberos":            "kerberos should not remain at internal top level",
		"/home/mrafter/nas-os/internal/kmip":                "kmip should not remain at internal top level",
		"/home/mrafter/nas-os/internal/kmipclient":          "kmipclient should not remain at internal top level",
		"/home/mrafter/nas-os/internal/knowledgebase":       "knowledgebase should not remain at internal top level",
		"/home/mrafter/nas-os/internal/knowledgemap":        "knowledgemap should not remain at internal top level",
		"/home/mrafter/nas-os/internal/ldap":                "ldap should not remain at internal top level",
		"/home/mrafter/nas-os/internal/linkaggbondadvisor":  "linkaggbondadvisor should not remain at internal top level",
		"/home/mrafter/nas-os/internal/loadbalancer":        "loadbalancer should not remain at internal top level",
		"/home/mrafter/nas-os/internal/localchat":           "localchat should not remain at internal top level",
		"/home/mrafter/nas-os/internal/localknowledgebase":  "localknowledgebase should not remain at internal top level",
		"/home/mrafter/nas-os/internal/mailserver":          "mailserver should not remain at internal top level",
		"/home/mrafter/nas-os/internal/media":               "media should not remain at internal top level",
		"/home/mrafter/nas-os/internal/mpiofc":              "mpiofc should not remain at internal top level",
		"/home/mrafter/nas-os/internal/nasdiscovery":        "nasdiscovery should not remain at internal top level",
		"/home/mrafter/nas-os/internal/netdatawidget":       "netdatawidget should not remain at internal top level",
		"/home/mrafter/nas-os/internal/notes":               "notes should not remain at internal top level",
		"/home/mrafter/nas-os/internal/nvmeof":              "nvmeof should not remain at internal top level",
		"/home/mrafter/nas-os/internal/nvmeofenhanced":      "nvmeofenhanced should not remain at internal top level",
		"/home/mrafter/nas-os/internal/securep2pshare":      "securep2pshare should not remain at internal top level",
		"/home/mrafter/nas-os/internal/selfheal":            "selfheal should not remain at internal top level",
		"/home/mrafter/nas-os/internal/sharelinks":          "sharelinks should not remain at internal top level",
		"/home/mrafter/nas-os/internal/ssdcache":            "ssdcache should not remain at internal top level",
		"/home/mrafter/nas-os/internal/storagemigration":    "storagemigration should not remain at internal top level",
		"/home/mrafter/nas-os/internal/storagetiering":      "storagetiering should not remain at internal top level",
		"/home/mrafter/nas-os/internal/teamworkspace":       "teamworkspace should not remain at internal top level",
		"/home/mrafter/nas-os/internal/trafficclassifier":   "trafficclassifier should not remain at internal top level",
		"/home/mrafter/nas-os/internal/usbreset":            "usbreset should not remain at internal top level",
		"/home/mrafter/nas-os/internal/ztna":                "ztna should not remain at internal top level",
	}
	for path, msg := range paths {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			if err == nil {
				t.Fatal(msg)
			}
			t.Fatalf("%s: unexpected stat error: %v", msg, err)
		}
	}
}

func TestModuleCatalogCoreOnlyFive(t *testing.T) {
	catalog := ModuleCatalogSnapshot()
	var cores []string
	for name, tier := range catalog {
		if tier == arch.ModuleTierCore {
			cores = append(cores, name)
		}
	}
	want := map[string]bool{
		moduleIdentity: true,
		moduleStorage:  true,
		moduleNetwork:  true,
		moduleSharing:  true,
		moduleSystem:   true,
	}
	if len(cores) != 5 {
		t.Fatalf("core modules = %v (len %d), want exactly 5", cores, len(cores))
	}
	for _, name := range cores {
		if !want[name] {
			t.Fatalf("unexpected core module %q", name)
		}
	}
}
