// Package localchat implements a local AI-powered communication suite
// inspired by Synology's ChatPlus and Meet. It provides secure, on-premises
// messaging, video conferencing, and AI-powered features.
package localchat

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log"
	"sync"
	"time"
)

// MessageType defines the type of chat message
type MessageType string

const (
	MessageText     MessageType = "text"
	MessageImage    MessageType = "image"
	MessageFile     MessageType = "file"
	MessageVideo    MessageType = "video"
	MessageAudio    MessageType = "audio"
	MessageSystem   MessageType = "system"
	MessageAISummary MessageType = "ai_summary"
)

// ChannelType defines the type of communication channel
type ChannelType string

const (
	ChannelDirect   ChannelType = "direct"   // 1-on-1 chat
	ChannelGroup    ChannelType = "group"     // Group chat
	ChannelTeam     ChannelType = "team"      // Team workspace
	ChannelAnnounce ChannelType = "announce"  // Announcement channel
)

// MeetingStatus represents the status of a video meeting
type MeetingStatus string

const (
	MeetingScheduled MeetingStatus = "scheduled"
	MeetingActive    MeetingStatus = "active"
	MeetingEnded     MeetingStatus = "ended"
	MeetingCancelled MeetingStatus = "cancelled"
)

// User represents a chat user
type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	Avatar    string    `json:"avatar,omitempty"`
	Status    string    `json:"status"` // online, away, busy, offline
	LastSeen  time.Time `json:"last_seen"`
	IsAdmin   bool      `json:"is_admin"`
	AIEnabled bool      `json:"ai_enabled"` // Enable AI features for this user
}

// Message represents a chat message
type Message struct {
	ID          string      `json:"id"`
	ChannelID   string      `json:"channel_id"`
	SenderID    string      `json:"sender_id"`
	Type        MessageType `json:"type"`
	Content     string      `json:"content"`
	Attachments []Attachment `json:"attachments,omitempty"`
	ReplyTo     string      `json:"reply_to,omitempty"` // ID of message being replied to
	EditedAt    *time.Time  `json:"edited_at,omitempty"`
	CreatedAt   time.Time   `json:"created_at"`
	IsAI        bool        `json:"is_ai"` // Generated by AI
	AIMetadata  *AIMeta     `json:"ai_metadata,omitempty"`
}

// Attachment represents a file attachment
type Attachment struct {
	ID       string `json:"id"`
	Filename string `json:"filename"`
	MimeType string `json:"mime_type"`
	Size     int64  `json:"size"`
	URL      string `json:"url"`
}

// AIMeta contains AI-related metadata
type AIMeta struct {
	Model       string  `json:"model,omitempty"`
	TokensUsed  int     `json:"tokens_used,omitempty"`
	Confidence  float64 `json:"confidence,omitempty"`
	Summarized  bool    `json:"summarized,omitempty"`
	Translated  bool    `json:"translated,omitempty"`
	TargetLang  string  `json:"target_lang,omitempty"`
}

// Channel represents a communication channel
type Channel struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Type        ChannelType `json:"type"`
	Description string      `json:"description,omitempty"`
	OwnerID     string      `json:"owner_id"`
	Members     []string    `json:"members"` // User IDs
	IsPrivate   bool        `json:"is_private"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	AIModerator bool        `json:"ai_moderator"` // AI auto-moderation enabled
}

// Meeting represents a video meeting
type Meeting struct {
	ID          string        `json:"id"`
	Title       string        `json:"title"`
	HostID      string        `json:"host_id"`
	Status      MeetingStatus `json:"status"`
	ScheduledAt time.Time     `json:"scheduled_at"`
	StartedAt   *time.Time    `json:"started_at,omitempty"`
	EndedAt     *time.Time    `json:"ended_at,omitempty"`
	Duration    time.Duration `json:"duration"`
	Participants []Participant `json:"participants"`
	IsRecorded  bool          `json:"is_recorded"`
	AITranscript bool         `json:"ai_transcript"` // Enable AI transcription
	MaxParticipants int       `json:"max_participants"`
}

// Participant represents a meeting participant
type Participant struct {
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"` // host, co_host, participant
	JoinedAt  time.Time `json:"joined_at"`
	LeftAt    *time.Time `json:"left_at,omitempty"`
	IsMuted   bool      `json:"is_muted"`
	IsVideoOn bool      `json:"is_video_on"`
}

// AIAssistant represents AI capabilities
type AIAssistant struct {
	Enabled     bool   `json:"enabled"`
	Model       string `json:"model"` // Local LLM model name
	MaxTokens   int    `json:"max_tokens"`
	Features    []AIFeature `json:"features"`
}

// AIFeature defines available AI features
type AIFeature string

const (
	AISummarize     AIFeature = "summarize"
	AITranslate     AIFeature = "translate"
	AISentiment     AIFeature = "sentiment"
	AISmartReply    AIFeature = "smart_reply"
	AITranscription AIFeature = "transcription"
	AIModeration    AIFeature = "moderation"
	AISearch        AIFeature = "search"
)

// ChatConfig contains localchat configuration
type ChatConfig struct {
	MaxFileSize      int64         `json:"max_file_size"`      // bytes
	MaxMessageLength int           `json:"max_message_length"`
	HistoryRetention time.Duration `json:"history_retention"`  // How long to keep messages
	EnableEncryption bool          `json:"enable_encryption"`
	EnableAI         bool          `json:"enable_ai"`
	AIModel          string        `json:"ai_model"`
	WebRTCEnabled    bool          `json:"webrtc_enabled"`
	MaxMeetingDuration time.Duration `json:"max_meeting_duration"`
}

// ChatService is the main localchat service
type ChatService struct {
	mu          sync.RWMutex
	config      ChatConfig
	users       map[string]*User
	channels    map[string]*Channel
	messages    map[string][]*Message // channelID -> messages
	meetings    map[string]*Meeting
	ai          *AIAssistant
	ctx         context.Context
	cancel      context.CancelFunc
	messageChan chan *Message
}

// NewChatService creates a new localchat service
func NewChatService(config ChatConfig) *ChatService {
	ctx, cancel := context.WithCancel(context.Background())
	
	service := &ChatService{
		config:      config,
		users:       make(map[string]*User),
		channels:    make(map[string]*Channel),
		messages:    make(map[string][]*Message),
		meetings:    make(map[string]*Meeting),
		ctx:         ctx,
		cancel:      cancel,
		messageChan: make(chan *Message, 1000),
	}
	
	if config.EnableAI {
		service.ai = &AIAssistant{
			Enabled:   true,
			Model:     config.AIModel,
			MaxTokens: 4096,
			Features: []AIFeature{
				AISummarize,
				AITranslate,
				AISmartReply,
				AITranscription,
			},
		}
	}
	
	return service
}

// Start begins the chat service
func (s *ChatService) Start() error {
	log.Println("[LocalChat] Starting local AI communication suite")
	
	// Start message processor
	go s.processMessages()
	
	// Start presence updater
	go s.updatePresence()
	
	log.Println("[LocalChat] Service started successfully")
	return nil
}

// Stop gracefully stops the service
func (s *ChatService) Stop() error {
	s.cancel()
	log.Println("[LocalChat] Service stopped")
	return nil
}

// RegisterUser registers a new user
func (s *ChatService) RegisterUser(username, fullName, email string) (*User, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	
	// Check if username exists
	for _, u := range s.users {
		if u.Username == username {
			return nil, fmt.Errorf("username already exists: %s", username)
		}
	}
	
	user := &User{
		ID:        generateID(),
		Username:  username,
		FullName:  fullName,
		Email:     email,
		Status:    "online",
		LastSeen:  time.Now(),
		AIEnabled: s.config.EnableAI,
	}
	
	s.users[user.ID] = user
	log.Printf("[LocalChat] User registered: %s (%s)", username, user.ID)
	
	return user, nil
}

// CreateChannel creates a new communication channel
func (s *ChatService) CreateChannel(name string, channelType ChannelType, ownerID string, isPrivate bool) (*Channel, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	
	if _, exists := s.users[ownerID]; !exists {
		return nil, fmt.Errorf("user not found: %s", ownerID)
	}
	
	channel := &Channel{
		ID:        generateID(),
		Name:      name,
		Type:      channelType,
		OwnerID:   ownerID,
		Members:   []string{ownerID},
		IsPrivate: isPrivate,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	
	s.channels[channel.ID] = channel
	s.messages[channel.ID] = make([]*Message, 0)
	
	log.Printf("[LocalChat] Channel created: %s (%s)", name, channel.ID)
	return channel, nil
}

// SendMessage sends a message to a channel
func (s *ChatService) SendMessage(channelID, senderID string, msgType MessageType, content string) (*Message, error) {
	s.mu.RLock()
	channel, exists := s.channels[channelID]
	if !exists {
		s.mu.RUnlock()
		return nil, fmt.Errorf("channel not found: %s", channelID)
	}
	
	// Check if sender is a member
	isMember := false
	for _, memberID := range channel.Members {
		if memberID == senderID {
			isMember = true
			break
		}
	}
	if !isMember {
		s.mu.RUnlock()
		return nil, fmt.Errorf("user %s is not a member of channel %s", senderID, channelID)
	}
	s.mu.RUnlock()
	
	message := &Message{
		ID:        generateID(),
		ChannelID: channelID,
		SenderID:  senderID,
		Type:      msgType,
		Content:   content,
		CreatedAt: time.Now(),
	}
	
	s.messageChan <- message
	return message, nil
}

// GetMessages retrieves messages from a channel
func (s *ChatService) GetMessages(channelID string, limit int, before *time.Time) ([]*Message, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	
	messages, exists := s.messages[channelID]
	if !exists {
		return nil, fmt.Errorf("channel not found: %s", channelID)
	}
	
	result := make([]*Message, 0)
	for i := len(messages) - 1; i >= 0 && len(result) < limit; i-- {
		if before != nil && messages[i].CreatedAt.After(*before) {
			continue
		}
		result = append(result, messages[i])
	}
	
	return result, nil
}

// ScheduleMeeting schedules a new video meeting
func (s *ChatService) ScheduleMeeting(title, hostID string, scheduledAt time.Time, maxParticipants int) (*Meeting, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	
	meeting := &Meeting{
		ID:              generateID(),
		Title:           title,
		HostID:          hostID,
		Status:          MeetingScheduled,
		ScheduledAt:     scheduledAt,
		AITranscript:    s.config.EnableAI,
		MaxParticipants: maxParticipants,
	}
	
	s.meetings[meeting.ID] = meeting
	log.Printf("[LocalChat] Meeting scheduled: %s at %v", title, scheduledAt)
	
	return meeting, nil
}

// StartMeeting starts a scheduled meeting
func (s *ChatService) StartMeeting(meetingID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	
	meeting, exists := s.meetings[meetingID]
	if !exists {
		return fmt.Errorf("meeting not found: %s", meetingID)
	}
	
	if meeting.Status != MeetingScheduled {
		return fmt.Errorf("meeting cannot be started, status: %s", meeting.Status)
	}
	
	now := time.Now()
	meeting.Status = MeetingActive
	meeting.StartedAt = &now
	
	log.Printf("[LocalChat] Meeting started: %s", meeting.Title)
	return nil
}

// JoinMeeting adds a participant to an active meeting
func (s *ChatService) JoinMeeting(meetingID, userID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	
	meeting, exists := s.meetings[meetingID]
	if !exists {
		return fmt.Errorf("meeting not found: %s", meetingID)
	}
	
	if meeting.Status != MeetingActive {
		return fmt.Errorf("meeting is not active")
	}
	
	if len(meeting.Participants) >= meeting.MaxParticipants {
		return fmt.Errorf("meeting is full")
	}
	
	participant := Participant{
		UserID:    userID,
		Role:      "participant",
		JoinedAt:  time.Now(),
		IsMuted:   false,
		IsVideoOn: true,
	}
	
	// Check if host
	if meeting.HostID == userID {
		participant.Role = "host"
	}
	
	meeting.Participants = append(meeting.Participants, participant)
	log.Printf("[LocalChat] User %s joined meeting %s", userID, meeting.Title)
	
	return nil
}

// AISummarizeMessages uses AI to summarize channel messages
func (s *ChatService) AISummarizeMessages(channelID string, timeRange time.Duration) (string, error) {
	if s.ai == nil || !s.ai.Enabled {
		return "", fmt.Errorf("AI features are not enabled")
	}
	
	s.mu.RLock()
	messages, exists := s.messages[channelID]
	if !exists {
		s.mu.RUnlock()
		return "", fmt.Errorf("channel not found")
	}
	s.mu.RUnlock()
	
	// Filter messages within time range
	cutoff := time.Now().Add(-timeRange)
	var recentMessages []*Message
	for _, msg := range messages {
		if msg.CreatedAt.After(cutoff) {
			recentMessages = append(recentMessages, msg)
		}
	}
	
	if len(recentMessages) == 0 {
		return "No messages to summarize", nil
	}
	
	// In real implementation, this would call local LLM
	summary := fmt.Sprintf("AI Summary of %d messages in the last %v", len(recentMessages), timeRange)
	log.Printf("[LocalChat] Generated AI summary for channel %s", channelID)
	
	return summary, nil
}

// AITranslateMessage translates a message to target language
func (s *ChatService) AITranslateMessage(messageID, targetLang string) (string, error) {
	if s.ai == nil || !s.ai.Enabled {
		return "", fmt.Errorf("AI features are not enabled")
	}
	
	// Find message
	s.mu.RLock()
	var message *Message
	for _, msgs := range s.messages {
		for _, msg := range msgs {
			if msg.ID == messageID {
				message = msg
				break
			}
		}
	}
	s.mu.RUnlock()
	
	if message == nil {
		return "", fmt.Errorf("message not found")
	}
	
	// In real implementation, this would call local LLM for translation
	translated := fmt.Sprintf("[Translated to %s] %s", targetLang, message.Content)
	log.Printf("[LocalChat] Translated message %s to %s", messageID, targetLang)
	
	return translated, nil
}

// AISmartReply generates smart reply suggestions
func (s *ChatService) AISmartReply(channelID string) ([]string, error) {
	if s.ai == nil || !s.ai.Enabled {
		return nil, fmt.Errorf("AI features are not enabled")
	}
	
	s.mu.RLock()
	messages, exists := s.messages[channelID]
	if !exists || len(messages) == 0 {
		s.mu.RUnlock()
		return nil, fmt.Errorf("no messages to generate replies for")
	}
	s.mu.RUnlock()
	
	// In real implementation, this would analyze recent messages and generate suggestions
	suggestions := []string{
		"Thanks for the update!",
		"I'll look into it.",
		"Sounds good to me.",
	}
	
	return suggestions, nil
}

// processMessages processes incoming messages
func (s *ChatService) processMessages() {
	for {
		select {
		case <-s.ctx.Done():
			return
		case msg := <-s.messageChan:
			s.mu.Lock()
			s.messages[msg.ChannelID] = append(s.messages[msg.ChannelID], msg)
			s.mu.Unlock()
			
			log.Printf("[LocalChat] Message processed: %s in channel %s", msg.ID, msg.ChannelID)
		}
	}
}

// updatePresence periodically updates user presence
func (s *ChatService) updatePresence() {
	ticker := time.NewTicker(30 * time.Second)
	defer ticker.Stop()
	
	for {
		select {
		case <-s.ctx.Done():
			return
		case <-ticker.C:
			// Update presence based on activity
		}
	}
}

// generateID generates a random ID
func generateID() string {
	bytes := make([]byte, 16)
	rand.Read(bytes)
	return hex.EncodeToString(bytes)
}

// GetServiceStatus returns the current service status
func (s *ChatService) GetServiceStatus() map[string]interface{} {
	s.mu.RLock()
	defer s.mu.RUnlock()
	
	return map[string]interface{}{
		"users":     len(s.users),
		"channels":  len(s.channels),
		"messages":  s.countMessages(),
		"meetings":  len(s.meetings),
		"ai_enabled": s.ai != nil && s.ai.Enabled,
	}
}

// countMessages counts total messages across all channels
func (s *ChatService) countMessages() int {
	count := 0
	for _, msgs := range s.messages {
		count += len(msgs)
	}
	return count
}
